### ISSUE TITLE
Does it work on 2.4.7?

### ISSUE THREAD

**Issue by live4soccer7** [btcpayserver/magento2-plugin#21]

**Comment by ndeet** [comment]
Hi, seems the payment method is not showing up on 2.4.7, will take a look and try to fix next week.

**Comment by live4soccer7** [comment]
Thanks!

**Comment by sonicode** [comment]
Any update on this issue?

**Comment by lightningcheckout** [comment]
@ndeet did you already look into this issue and have any idea of the root cause?

I did run some tests today:

- 2.4.6-p8 installed directly: working fine
- 2.4.6-p8 updated to 2.4.7-p2: BTC payment option doesn't show
- 2.4.7-p2 installed directly: not able to configure the plugin. During the redirect when the API key in BTCpay is set, an error occured. 
  - one instance gives a 'forbidden' error.
  - other instance gives the error below

```
ERROR: Warning: Cannot modify header information - headers already sent by (output started at /data/web/staging/vendor/btcpayserver/magento2-btcpay-module/Controller/Apikey/Save.php:107) in /data/web/staging/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php on line 143
```

Perhaps this can be of help.

**Comment by lightningcheckout** [comment]
The webhook secret couldn't be retrieved, should be fixed by:
https://github.com/btcpayserver/magento2-plugin/pull/25

**Comment by ndeet** [comment]
Hey there, I suspected CSP enforcment to be the issue but I switched off all CSP and the issue is still there so it seems to be something else. Spent quite some time checking if other payment plugins had specific updates to make them compatible with 2.4.7 but there are no obvious ones. Really strange that the payment method does not show up. Will do some more debugging.

**Comment by lightningcheckout** [comment]
> Hey there, I suspected CSP enforcment to be the issue but I switched off all CSP and the issue is still there so it seems to be something else. Spent quite some time checking if other payment plugins had specific updates to make them compatible with 2.4.7 but there are no obvious ones. Really strange that the payment method does not show up. Will do some more debugging.

While looking for the root cause of #24 it appeared that on every refresh of the BTCpay setup page the secret in the database was changing. That's the fix I've made. After that, this issue was also resolved on my end. But not sure if that make sense?
